--Nome: Caike Dametto RM: 558614
--Nome: Guilhetme Janunzzi RM: 558461

DROP TABLE IF EXISTS T_MM_MOVIMENTACAO;
GO
DROP TABLE IF EXISTS T_MM_HISTORICO_POSICAO;
GO
DROP TABLE IF EXISTS T_MM_PROBLEMA;
GO
DROP TABLE IF EXISTS T_MM_MOTO;
GO
DROP TABLE IF EXISTS T_MM_POSICAO_PATIO;
GO
DROP TABLE IF EXISTS T_MM_USUARIO;
GO
DROP TABLE IF EXISTS T_MM_FILIAL;
GO