--Nome: Caike Dametto RM: 558614
--Nome: Guilhetme Janunzzi RM: 558461

CREATE TABLE T_MM_FILIAL (
    CD_FILIAL           INT IDENTITY(1,1) NOT NULL,
    NM_FILIAL           VARCHAR(150) NOT NULL,
    DS_ENDERECO         VARCHAR(255) NOT NULL,
    NM_CIDADE           VARCHAR(100) NOT NULL,
    SG_ESTADO           VARCHAR(2) NOT NULL,
    NR_LINHA            SMALLINT NOT NULL,
    NR_COLUNA           SMALLINT NOT NULL,
    QT_CAPACIDADE_MAX   INT NOT NULL,
    CONSTRAINT PK_FILIAL_MOTOMAP PRIMARY KEY (CD_FILIAL)
);

GO

CREATE TABLE T_MM_USUARIO (
    CD_USUARIO          INT IDENTITY(1,1) NOT NULL,
    CD_FILIAL           INT NOT NULL,
    NM_USUARIO          VARCHAR(150) NOT NULL,
    DS_EMAIL            VARCHAR(100) NOT NULL,
    DS_SENHA            VARCHAR(200) NOT NULL,
    DS_CARGO            VARCHAR(20) NOT NULL,
    CONSTRAINT PK_USUARIO_MOTOMAP PRIMARY KEY (CD_USUARIO),
    CONSTRAINT FK_CD_FILIAL_USUARIO FOREIGN KEY (CD_FILIAL) REFERENCES T_MM_FILIAL (CD_FILIAL)
);

GO

CREATE TABLE T_MM_POSICAO_PATIO (
    CD_POSICAO          INT IDENTITY(1,1) NOT NULL,
    CD_FILIAL           INT NOT NULL,
    CD_IDENTIFICACAO    VARCHAR(10) NOT NULL,
    NR_LINHA            SMALLINT NOT NULL,
    NR_COLUNA           SMALLINT NOT NULL,
    DS_AREA             VARCHAR(50) NOT NULL,
    DS_OCUPADO          BIT NOT NULL DEFAULT 0,
    CONSTRAINT PK_POSICAO_MOTOMAP PRIMARY KEY (CD_POSICAO),
    CONSTRAINT FK_CD_FILIAL_POSICAO FOREIGN KEY (CD_FILIAL) REFERENCES T_MM_FILIAL (CD_FILIAL)
);

GO

CREATE TABLE T_MM_MOTO (
    CD_MOTO             INT IDENTITY(1,1) NOT NULL,
    CD_FILIAL           INT NOT NULL,
    DS_PLACA            VARCHAR(8),
    DS_CHASSI           VARCHAR(17),  
    NM_MODELO           VARCHAR(50) NOT NULL,
    NR_ANO              SMALLINT NOT NULL,
    DS_STATUS           VARCHAR(20) NOT NULL,
    CONSTRAINT PK_MOTO_MOTOMAP PRIMARY KEY (CD_MOTO),
    CONSTRAINT FK_CD_FILIAL_MOTO FOREIGN KEY (CD_FILIAL) REFERENCES T_MM_FILIAL (CD_FILIAL)
);

GO

CREATE TABLE T_MM_PROBLEMA (
    CD_PROBLEMA         INT IDENTITY(1,1) NOT NULL,
    CD_MOTO             INT NOT NULL,
    CD_USUARIO          INT NOT NULL,
    DS_TIPO             VARCHAR(20) NOT NULL,
    DS_DESCRICAO        VARCHAR(255) NOT NULL,
    DT_REGISTRO         DATETIME NOT NULL DEFAULT GETDATE(),
    DS_RESOLVIDO        BIT NOT NULL DEFAULT 0,
    CONSTRAINT PK_PROBLEMA_MOTOMAP PRIMARY KEY (CD_PROBLEMA),
    CONSTRAINT FK_MOTO_PROBLEMA FOREIGN KEY (CD_MOTO) REFERENCES T_MM_MOTO (CD_MOTO),
    CONSTRAINT FK_USUARIO_PROBLEMA FOREIGN KEY (CD_USUARIO) REFERENCES T_MM_USUARIO (CD_USUARIO)
);

GO